
package com.mycompany.gamezonepro.vista;

import com.mycompany.gamezonepro.controlador.*;
import com.mycompany.gamezonepro.modelo.*;
import com.mycompany.gamezonepro.modelo.estructuras.MallaOrtogonal;

public class MenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());
    private ControlUsuarios sisu;
    private Usuario usuarioActual;
    private ControlRecompensas sisr;
   
   
    public MenuPrincipal(ControlUsuarios sisu, Usuario usuarioActual) {
        this.sisu = sisu;
        this.usuarioActual = usuarioActual; 
        sisr = new ControlRecompensas(usuarioActual);
        sisr.gestionLogros(usuarioActual.getCompras(), usuarioActual.getAlbum().getMalla().contarCartas(usuarioActual.getAlbum().getMalla().getNodo(0, 0)), 
                usuarioActual.getXp(), usuarioActual.getGastos(), null);
        initComponents();
        inicializar();
        nivelBarra();
    }
    
    public void inicializar(){
        UsuarioTxt.setText(usuarioActual.getId());
        
    }   
    
    public void nivelBarra(){
        if (usuarioActual.getXp()>-1 && usuarioActual.getXp()<500){
            barra.setMaximum(500);
            barra.setValue(usuarioActual.getXp());
            ContxpTxt.setText(String.valueOf(usuarioActual.getXp())+"/500");
            NivelTxt.setText("Aprendiz - "+String.valueOf(usuarioActual.getXp())+"xp");
        }
        else if (usuarioActual.getXp()>499 && usuarioActual.getXp()<1500){
            barra.setMaximum(1001);
            barra.setValue(usuarioActual.getXp()-500);
            ContxpTxt.setText(String.valueOf(usuarioActual.getXp()-500)+"/1000");
            NivelTxt.setText("Jugador - "+String.valueOf(usuarioActual.getXp())+"xp");
        }
        else if (usuarioActual.getXp()>1499 && usuarioActual.getXp()<3500){
            barra.setMaximum(2003);
            barra.setValue(usuarioActual.getXp()-1500);
            ContxpTxt.setText(String.valueOf(usuarioActual.getXp()-1500)+"/2000");
            NivelTxt.setText("Veterano - "+String.valueOf(usuarioActual.getXp())+"xp");
        }
        else if (usuarioActual.getXp()>3499 && usuarioActual.getXp()<7000){
            barra.setMaximum(3506);
            barra.setValue(usuarioActual.getXp()-3500);
            ContxpTxt.setText(String.valueOf(usuarioActual.getXp()-3500)+"/3500");
            NivelTxt.setText("Maestro - "+String.valueOf(usuarioActual.getXp())+"xp");
        }
        else if (usuarioActual.getXp()>6999){
            barra.setMaximum(7000);
            barra.setValue(7000);
            ContxpTxt.setText("7000/7000+");
            NivelTxt.setText("Leyenda - "+String.valueOf(usuarioActual.getXp())+"xp");
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        UsuarioTxt = new javax.swing.JLabel();
        NivelTxt = new javax.swing.JLabel();
        barra = new javax.swing.JProgressBar();
        ContxpTxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TiendaBtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        AlbumBtn = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        EventosBtn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        GamiBtn = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ReporteBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        InfoBtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        SesionBtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("GameZone Pro");

        jLabel2.setText("IPC1 - Proyecto 2");

        jLabel3.setText("Progreso nivel: ");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        UsuarioTxt.setText("Nombre");

        NivelTxt.setText("Nivel y xp");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UsuarioTxt)
                    .addComponent(NivelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(UsuarioTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NivelTxt)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        ContxpTxt.setText("0/0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContxpTxt)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ContxpTxt)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(barra, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel6.setText("Modulos del Sistema");

        TiendaBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TiendaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TiendaBtnMouseClicked(evt);
            }
        });

        jLabel7.setText("Tienda");

        javax.swing.GroupLayout TiendaBtnLayout = new javax.swing.GroupLayout(TiendaBtn);
        TiendaBtn.setLayout(TiendaBtnLayout);
        TiendaBtnLayout.setHorizontalGroup(
            TiendaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TiendaBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        TiendaBtnLayout.setVerticalGroup(
            TiendaBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TiendaBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        AlbumBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AlbumBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlbumBtnMouseClicked(evt);
            }
        });

        jLabel8.setText("Album");

        javax.swing.GroupLayout AlbumBtnLayout = new javax.swing.GroupLayout(AlbumBtn);
        AlbumBtn.setLayout(AlbumBtnLayout);
        AlbumBtnLayout.setHorizontalGroup(
            AlbumBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlbumBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        AlbumBtnLayout.setVerticalGroup(
            AlbumBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlbumBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        EventosBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EventosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EventosBtnMouseClicked(evt);
            }
        });

        jLabel9.setText("Eventos");

        javax.swing.GroupLayout EventosBtnLayout = new javax.swing.GroupLayout(EventosBtn);
        EventosBtn.setLayout(EventosBtnLayout);
        EventosBtnLayout.setHorizontalGroup(
            EventosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EventosBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        EventosBtnLayout.setVerticalGroup(
            EventosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EventosBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        GamiBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        GamiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GamiBtnMouseClicked(evt);
            }
        });

        jLabel10.setText("Gamificacion");

        javax.swing.GroupLayout GamiBtnLayout = new javax.swing.GroupLayout(GamiBtn);
        GamiBtn.setLayout(GamiBtnLayout);
        GamiBtnLayout.setHorizontalGroup(
            GamiBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamiBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GamiBtnLayout.setVerticalGroup(
            GamiBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamiBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        ReporteBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ReporteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReporteBtnMouseClicked(evt);
            }
        });

        jLabel11.setText("Reportes");

        javax.swing.GroupLayout ReporteBtnLayout = new javax.swing.GroupLayout(ReporteBtn);
        ReporteBtn.setLayout(ReporteBtnLayout);
        ReporteBtnLayout.setHorizontalGroup(
            ReporteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReporteBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        ReporteBtnLayout.setVerticalGroup(
            ReporteBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReporteBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        InfoBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        InfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InfoBtnMouseClicked(evt);
            }
        });

        jLabel12.setText("Estudiante");

        javax.swing.GroupLayout InfoBtnLayout = new javax.swing.GroupLayout(InfoBtn);
        InfoBtn.setLayout(InfoBtnLayout);
        InfoBtnLayout.setHorizontalGroup(
            InfoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        InfoBtnLayout.setVerticalGroup(
            InfoBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        SesionBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SesionBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SesionBtnMouseClicked(evt);
            }
        });

        jLabel4.setText("Cerrar Sesion");

        javax.swing.GroupLayout SesionBtnLayout = new javax.swing.GroupLayout(SesionBtn);
        SesionBtn.setLayout(SesionBtnLayout);
        SesionBtnLayout.setHorizontalGroup(
            SesionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SesionBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SesionBtnLayout.setVerticalGroup(
            SesionBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SesionBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SesionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TiendaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GamiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ReporteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AlbumBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EventosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlbumBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TiendaBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EventosBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GamiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReporteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SesionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TiendaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TiendaBtnMouseClicked
       java.awt.EventQueue.invokeLater(() -> {
        this.dispose();
        new Tienda(sisu, usuarioActual, sisr).setVisible(true);
    });
    }//GEN-LAST:event_TiendaBtnMouseClicked

    private void AlbumBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlbumBtnMouseClicked

        java.awt.EventQueue.invokeLater(() -> {
        this.dispose();
        new Album(sisu, usuarioActual).setVisible(true);
    });
    }//GEN-LAST:event_AlbumBtnMouseClicked

    private void EventosBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EventosBtnMouseClicked
        java.awt.EventQueue.invokeLater(() -> {
        this.dispose();
        new Torneos(sisu, usuarioActual).setVisible(true);
    });
    }//GEN-LAST:event_EventosBtnMouseClicked

    private void GamiBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GamiBtnMouseClicked
        java.awt.EventQueue.invokeLater(() -> {
        this.dispose();
        new Recompensas(sisu, usuarioActual).setVisible(true);
    });
    }//GEN-LAST:event_GamiBtnMouseClicked

    private void ReporteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReporteBtnMouseClicked
        java.awt.EventQueue.invokeLater(() -> {
        this.dispose();
        new Reportes(sisu, usuarioActual).setVisible(true);
    });
    }//GEN-LAST:event_ReporteBtnMouseClicked

    private void InfoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoBtnMouseClicked
        java.awt.EventQueue.invokeLater(() -> {
        this.dispose();
        new Informacion(sisu, usuarioActual).setVisible(true);
    });
    }//GEN-LAST:event_InfoBtnMouseClicked

    private void SesionBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SesionBtnMouseClicked
        java.awt.EventQueue.invokeLater(() -> {
        this.dispose();
        new Login(sisu).setVisible(true);
    });
    }//GEN-LAST:event_SesionBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AlbumBtn;
    private javax.swing.JLabel ContxpTxt;
    private javax.swing.JPanel EventosBtn;
    private javax.swing.JPanel GamiBtn;
    private javax.swing.JPanel InfoBtn;
    private javax.swing.JLabel NivelTxt;
    private javax.swing.JPanel ReporteBtn;
    private javax.swing.JPanel SesionBtn;
    private javax.swing.JPanel TiendaBtn;
    private javax.swing.JLabel UsuarioTxt;
    private javax.swing.JProgressBar barra;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
